#!/usr/bin/env bash
# This script will:
# When passing the argument start:
#     Starts manage_my_process
#     Creates a file containing its PID in /var/run/my_process.pid
#     Displays manage_my_process started
# When passing the argument stop: 
#     Stops manage_my_process
#     Deletes the file /var/run/my_process.pid
#     Displays manage_my_process stopped
# When passing the argument restart
#     Stops manage_my_process
#     Deletes the file /var/run/my_process.pid
#     Starts manage_my_process
#     Creates a file containing its PID in /var/run/my_process.pid
#     Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
case $1 in
    "start")
        ./manage_my_process &
	sudo sh -c 'echo $$ > /var/run/my_process.pid'
	echo "manage_my_process started"
    ;;
    "stop")
        pkill -SIGTERM -f "./manage_my_process"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
    ;;
    "restart")
        pkill -SIGTERM -f "./manage_my_process"
	if [ -e /var/run/my_process.pid ];
	then
	    sudo rm /var/run/my_process.pid
	fi
        ./manage_my_process &
	sudo sh -c 'echo $$ > /var/run/my_process.pid'
	echo "manage_my_process restarted"
    ;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
